package de.pocketcloud.cloud.server.config;

import de.pocketcloud.cloud.util.ArrayUtils;
import de.pocketcloud.cloud.util.FileUtils;

import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

public abstract class ServerProperties implements IServerProperties {

    protected boolean modifyYaml(String filePath, Map<String, Object> updatedContent) {
        try {
            Map<String, Object> content = loadYaml(filePath);
            content.putAll(updatedContent);
            return saveYaml(filePath, content);
        } catch (Exception e) {
            return false;
        }
    }

    protected boolean renewYaml(String filePath) {
        try {
            Map<String, Object> content = loadYaml(filePath);
            ArrayUtils.fillMissingKeys(content, getDefaultContent());
            return saveYaml(filePath, content);
        } catch (Exception e) {
            return false;
        }
    }

    protected boolean needsRenewalYaml(String filePath) {
        if (!Files.exists(Path.of(filePath))) return true;
        try {
            Map<String, Object> content = loadYaml(filePath);
            return !ArrayUtils.hasAllKeys(content, getDefaultContent());
        } catch (Exception e) {
            return true;
        }
    }

    protected boolean modifyProperties(String filePath, Map<String, Object> updatedContent) {
        try {
            Properties props = loadProperties(filePath);
            updatedContent.forEach((k, v) -> props.setProperty(k, String.valueOf(v)));
            return saveProperties(filePath, props);
        } catch (Exception e) {
            return false;
        }
    }

    protected boolean renewProperties(String filePath) {
        try {
            Properties props = loadProperties(filePath);
            getDefaultContent().forEach((k, v) -> {
                if (!props.containsKey(k)) props.setProperty(k, String.valueOf(v));
            });
            return saveProperties(filePath, props);
        } catch (Exception e) {
            return false;
        }
    }

    protected boolean needsRenewalProperties(String filePath) {
        if (!Files.exists(Path.of(filePath))) return true;
        try {
            Properties props = loadProperties(filePath);
            return getDefaultContent().keySet().stream().anyMatch(k -> !props.containsKey(k));
        } catch (Exception e) {
            return true;
        }
    }

    private Map<String, Object> loadYaml(String filePath) {
        Path path = Path.of(filePath);
        if (!Files.exists(path)) return new LinkedHashMap<>(getDefaultContent());
        Map<String, Object> loaded = FileUtils.parseYamlFile(path);
        return loaded != null ? loaded : new LinkedHashMap<>();
    }

    private boolean saveYaml(String filePath, Map<String, Object> content) {
        return FileUtils.emitYamlFile(Path.of(filePath), content);
    }

    private Properties loadProperties(String filePath) throws IOException {
        Properties props = new Properties();
        Path path = Path.of(filePath);
        if (Files.exists(path)) {
            List<String> lines = Files.readAllLines(path);
            StringBuilder sb = new StringBuilder();
            for (String line : lines) {
                if (!line.startsWith("#")) sb.append(line).append("\n");
            }

            props.load(new StringReader(sb.toString()));
        }
        return props;
    }

    private boolean saveProperties(String filePath, Properties props) {
        try {
            StringBuilder sb = new StringBuilder();
            sb.append("# Auto-generated by PocketCloud\n");
            getDefaultContent().forEach((k, v) -> {
                String val = props.getProperty(k, String.valueOf(v));
                sb.append(k).append("=").append(val).append("\n");
            });
            props.forEach((k, v) -> {
                if (!getDefaultContent().containsKey(k.toString())) {
                    sb.append(k).append("=").append(v).append("\n");
                }
            });
            Files.writeString(Path.of(filePath), sb.toString());
            return true;
        } catch (IOException e) {
            return false;
        }
    }
}