name: Build Status

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main", "v4" ]

jobs:
  php:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, json
          coverage: none

      - name: PHP Syntax Check
        run: find . -name "*.php" -exec php -l {} \;